### ISSUE TITLE
Missing Spinner

### ISSUE THREAD

**Issue by jimmyz** [rootsdev/familysearch-reference-client#3]
While the tree view is waiting for a request to fulfill, I'm not seeing a spinner. This happens when I navigate from a profile view to the tree view of that person.

![demo_werelate_org___tree_kw8w-rfd](https://cloud.githubusercontent.com/assets/32701/3462281/dfe33472-022b-11e4-9727-37110fa2aead.png)

**Comment by lmonson** [comment]
I added wait spinners.  You should see these on the next deployment.
